api:
  dashboard: true
  insecure: true
###################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
###################
providers:
  docker: {}
###################
log:
  level: INFO
