version: '3'
services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls-config/:/etc/traefik/tls-config/
      - ./certs/:/etc/traefik/certs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.isc`)"
      - "traefik.http.routers.dashboard.middlewares=traefik-redirectscheme"
      - "traefik.http.routers.dashboard-secure.entrypoints=websecure"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.service=api@internal"
      - "traefik.http.routers.dashboard-secure.rule=Host(`traefik.isc`)"
      - "traefik.http.routers.dashboard-secure.middlewares=traefik-auth"
      - "traefik.http.services.dashboard-secure.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$v34sL/e2$$gS78OBDiM3vBejYIbqQSa.,mohammad:$$apr1$$pt3kthOX$$V3iBg7dix/veW1dTcvyuO."
      - "traefik.http.middlewares.traefik-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-redirectscheme.redirectscheme.permanent=true"
  vault:
    image: hashicorp/vault
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=myroottoken"
      - "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200"
    ports:
     - "8200:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.isc`)"
      - "traefik.http.routers.vault.entrypoints=web"
      - "traefik.http.routers.vault.middlewares=vault-redirectscheme"
      - "traefik.http.routers.vault-secure.tls=true"
      - "traefik.http.routers.vault-secure.rule=Host(`vault.isc`)"
      - "traefik.http.routers.vault-secure.entrypoints=websecure"
      - "traefik.http.routers.vault-secure.middlewares=vault-auth,vault-errors"
      - "traefik.http.services.vault-secure.loadbalancer.server.port=8200"
      - "traefik.http.middlewares.vault-auth.basicauth.users=admin:$$apr1$$v34sL/e2$$gS78OBDiM3vBejYIbqQSa.,test:$$apr1$$FL3X.JsO$$TKGdO4WlcAk61e6K3p8Au1"
      - "traefik.http.middlewares.vault-errors.errors.status=400-599"
      - "traefik.http.middlewares.vault-errors.errors.service=error"
      - "traefik.http.middlewares.vault-errors.errors.query=/{status}.html"
      - "traefik.http.middlewares.vault-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.vault-redirectscheme.redirectscheme.permanent=true"
  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.entrypoints=web"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.routers.error.rule=Host(`error.localhost`)"
      - "traefik.http.services.error.loadbalancer.server.port=80"
